### ISSUE TITLE
APXS

### ISSUE THREAD

**Issue by rayenmessaoudi** [SpiderLabs/ModSecurity-apache#35]
any one can help for this issue : 
configure: looking for Apache module support via DSO through APXS

**Comment by zimmerle** [comment]
There is a config.log which contains all the info related to the dependencies in your setup. Do you mind to share via gits?

**Comment by rayenmessaoudi** [comment]
this is the config file inside ModSecurity-apache
https://gist.github.com/rayenmessaoudi/3e3dc3d610be870b3f418fa4ecdd3ab6
and this is inside ModSecurity
https://gist.github.com/rayenmessaoudi/3caaa10ae0f0531fef39a00e56975403

**Comment by zimmerle** [comment]
@rayenmessaoudi do you have httpd fully workable in your system?

**Comment by fosiul** [comment]
Hi, 
I am not sure if I am allowed to post here as it has been created by some one else, but just wanted to confirm, I am compiling in ubuntu 16.04   and having the same issues. 
httpd is working fine , 
do we need to pass any parameter with the configure ?

**Ubuntu Version :**
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

**Apache 2 Status**

● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: active (running) since Sun 2018-07-01 10:51:43 BST; 10min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 18784 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 18805 ExecStart=/etc/init.d/apache2 start (code=exited, status=0/SUCCESS)
   Memory: 54.2M
   CGroup: /system.slice/apache2.service
           ├─18820 /usr/sbin/apache2 -k start
           ├─18823 /usr/sbin/apache2 -k start
           ├─18824 /usr/sbin/apache2 -k start
           └─18826 /usr/sbin/apache2 -k start

Jul 01 10:51:42 project systemd[1]: Starting LSB: Apache2 web server...
Jul 01 10:51:42 project apache2[18805]:  * Starting Apache httpd web server apache2
Jul 01 10:51:42 project apache2[18805]: [Sun Jul 01 10:51:42.348245 2018] [so:warn] [pid 18819] AH01574: module dav_module is already loaded, skipping
Jul 01 10:51:43 project apache2[18805]:  *
Jul 01 10:51:43 project systemd[1]: Started LSB: Apache2 web server.

**Compiling Error:**
yuma@project:~/ModSecurity-apache$ sudo ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: looking for Apache module support via DSO through APXS
configure: found APXS at /usr/bin/apxs2
configure: looking for libmodsecurity
configure: found libmodsecurity at /usr/local/modsecurity//lib/
checking if apache is wanted... yes
checking for httpd... no
configure: error: "apache server executable not found"
yuma@project:~/ModSecurity-apache$

**Comment by Clement-Ruiz** [comment]
Hello.
@fosiul try `ln -s /usr/sbin/apache2 /usr/sbin/httpd` before installing Modsecurity-Apache.
I did this on ubuntu 18.04, using this [Dockerfile](https://github.com/CRS-support/modsecurity-docker/blob/v3/ubuntu-apache/Dockerfile).
You can try aswell on ubuntu 16.04, but some dependencies might be missing.

Hope it helped.

**Comment by zimmerle** [comment]
If your Apache is not following the standard installation, you may want to use: ```–with-apache=/path/to/your/httpd```
